#!/bin/bash

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a Thunderbird desktop='^2' follow=on
bspc rule -a TelegramDesktop desktop='^3' follow=on
bspc rule -a discord desktop='^3' follow=on
bspc rule -a Gimp state=tiled desktop='^4' follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Lemon Bar
$XDG_CONFIG_HOME/lemonbar/lemonbar.sh
